# Generated by Django 5.1.6 on 2025-02-15 04:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_controle', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Funcionario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cargo', models.CharField(max_length=100, verbose_name='Cargo')),
                ('salario', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Salário')),
                ('data_admissao', models.DateField(verbose_name='Data de Admissão')),
                ('departamento', models.CharField(max_length=100, verbose_name='Departamento')),
                ('carga_horaria', models.IntegerField(verbose_name='Carga Horária Semanal (horas)')),
                ('pessoa', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='app_controle.pessoa', verbose_name='Pessoa')),
            ],
        ),
    ]
