# Generated by Django 5.1.6 on 2025-02-15 15:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_controle', '0002_funcionario'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='funcionario',
            name='carga_horaria',
        ),
        migrations.RemoveField(
            model_name='funcionario',
            name='cargo',
        ),
        migrations.RemoveField(
            model_name='funcionario',
            name='departamento',
        ),
        migrations.RemoveField(
            model_name='funcionario',
            name='salario',
        ),
        migrations.AddField(
            model_name='funcionario',
            name='funcao',
            field=models.CharField(default='Não informado', max_length=100, verbose_name='Funcao'),
        ),
    ]
